### ISSUE TITLE
Generate markup too?

### ISSUE THREAD

**Issue by bebraw** [antwarjs/prevnext-plugin#1]
To make it easier to use this plugin should probably be able to generate some markup if wanted. Need to figure out how that would work. Now it's a little painful to use.

**Comment by eldh** [comment]
Maybe a `getComponent(s)` function that returns a (map of) react component(s)?

**Comment by bebraw** [comment]
Done. Feel free to tweak CSS names to your liking. I'll adapt.

**Comment by eldh** [comment]
Hm, not sure about this. Now the bodyContent is not optional, so theming this in a flexible way becomes pretty tricky.

**Comment by bebraw** [comment]
> Hm, not sure about this. Now the bodyContent is not optional, so theming this in a flexible way becomes pretty tricky.

I can provide a plugin level hook to override the default in case you need something arbitrary. I mean something like `prevnextPlugin({content: ...})`.

**Comment by eldh** [comment]
If I understand correctly:  This would only help with half of the problem, since bodyContent is still inserted on all pages. Also, that means the user will have to do some tricky config stuff.

**Comment by bebraw** [comment]
> If I understand correctly: This would only help with half of the problem, since bodyContent is still inserted on all pages. Also, that means the user will have to do some tricky config stuff.

Could be. Alternatively we could make `prevnext` bodyContent opt-in instead of opt-out. So markup wouldn't be generated by default but there would be a factory you could use if you are happy with the defaults. Would that work for you?

**Comment by eldh** [comment]
Yeah, making it opt-in would work.
