### ISSUE TITLE
Expose prev/next texts to user

### ISSUE THREAD

**Issue by bebraw** [antwarjs/prevnext-plugin#2]
This way I could show prev/next chapter names instead of just generic texts.

**Comment by eldh** [comment]
It would be up to the theme what should be rendered?

**Comment by eldh** [comment]
If we have a factory to generate bodyContent, then that could take arguments to customize the output.

**Comment by bebraw** [comment]
Yeah, I'll push it to a factory. The implementation will be close to the current commit.

**Comment by bebraw** [comment]
Done. The default case is very simple now. Using the factory takes some effort.

**Comment by eldh** [comment]
Looks good!
